;;;; Auto-generated Common Lisp shader bindings
;;;; DO NOT EDIT - generated by sokol-shdc

(defpackage #:example-wrapper-triangle
  (:use #:cl)
  (:export #:triangle-shader-desc
           #:+attr-triangle-position+
           #:+attr-triangle-color0+
           #:run-triangle-example))

(in-package :example-wrapper-triangle)

#|
    #version:1# (machine generated, don't edit!)

    Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

    Cmdline:
        sokol-shdc --input triangle-sapp.glsl --output triangle-shader.lisp --slang metal_macos --format sokol_lisp

    Overview:
    =========
    Shader program: 'triangle':
        Get shader desc: (triangle-shader-desc (sg:query-backend))
        Vertex Shader: vs
        Fragment Shader: fs
        Attributes:
            +ATTR_TRIANGLE_POSITION => 0
            +ATTR_TRIANGLE_COLOR0 => 1
    Bindings:
|#
(defconstant +ATTR_TRIANGLE_POSITION 0)
(defconstant +ATTR_TRIANGLE_COLOR0 1)
#|
    #include <metal_stdlib>
    #include <simd/simd.h>

    using namespace metal;

    struct main0_out
    {
        float4 color [[user(locn0)]];
        float4 gl_Position [[position]];
    };

    struct main0_in
    {
        float4 position [[attribute(0)]];
        float4 color0 [[attribute(1)]];
    };

    vertex main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.gl_Position = in.position;
        out.color = in.color0;
        return out;
    }

|#
;; Shader source for VS_SOURCE_METAL_MACOS (metal_macos)
(defparameter +vs_source_metal_macos+
  #(
    35 105 110 99 108 117 100 101 32 60 109 101 116 97 108 95 
    115 116 100 108 105 98 62 10 35 105 110 99 108 117 100 101 
    32 60 115 105 109 100 47 115 105 109 100 46 104 62 10 10 
    117 115 105 110 103 32 110 97 109 101 115 112 97 99 101 32 
    109 101 116 97 108 59 10 10 115 116 114 117 99 116 32 109 
    97 105 110 48 95 111 117 116 10 123 10 32 32 32 32 102 
    108 111 97 116 52 32 99 111 108 111 114 32 91 91 117 115 
    101 114 40 108 111 99 110 48 41 93 93 59 10 32 32 32 
    32 102 108 111 97 116 52 32 103 108 95 80 111 115 105 116 
    105 111 110 32 91 91 112 111 115 105 116 105 111 110 93 93 
    59 10 125 59 10 10 115 116 114 117 99 116 32 109 97 105 
    110 48 95 105 110 10 123 10 32 32 32 32 102 108 111 97 
    116 52 32 112 111 115 105 116 105 111 110 32 91 91 97 116 
    116 114 105 98 117 116 101 40 48 41 93 93 59 10 32 32 
    32 32 102 108 111 97 116 52 32 99 111 108 111 114 48 32 
    91 91 97 116 116 114 105 98 117 116 101 40 49 41 93 93 
    59 10 125 59 10 10 118 101 114 116 101 120 32 109 97 105 
    110 48 95 111 117 116 32 109 97 105 110 48 40 109 97 105 
    110 48 95 105 110 32 105 110 32 91 91 115 116 97 103 101 
    95 105 110 93 93 41 10 123 10 32 32 32 32 109 97 105 
    110 48 95 111 117 116 32 111 117 116 32 61 32 123 125 59 
    10 32 32 32 32 111 117 116 46 103 108 95 80 111 115 105 
    116 105 111 110 32 61 32 105 110 46 112 111 115 105 116 105 
    111 110 59 10 32 32 32 32 111 117 116 46 99 111 108 111 
    114 32 61 32 105 110 46 99 111 108 111 114 48 59 10 32 
    32 32 32 114 101 116 117 114 110 32 111 117 116 59 10 125 
    10 10 0))

#|
    #include <metal_stdlib>
    #include <simd/simd.h>

    using namespace metal;

    struct main0_out
    {
        float4 frag_color [[color(0)]];
    };

    struct main0_in
    {
        float4 color [[user(locn0)]];
    };

    fragment main0_out main0(main0_in in [[stage_in]])
    {
        main0_out out = {};
        out.frag_color = in.color;
        return out;
    }

|#
;; Shader source for FS_SOURCE_METAL_MACOS (metal_macos)
(defparameter +fs_source_metal_macos+
  #(
    35 105 110 99 108 117 100 101 32 60 109 101 116 97 108 95 
    115 116 100 108 105 98 62 10 35 105 110 99 108 117 100 101 
    32 60 115 105 109 100 47 115 105 109 100 46 104 62 10 10 
    117 115 105 110 103 32 110 97 109 101 115 112 97 99 101 32 
    109 101 116 97 108 59 10 10 115 116 114 117 99 116 32 109 
    97 105 110 48 95 111 117 116 10 123 10 32 32 32 32 102 
    108 111 97 116 52 32 102 114 97 103 95 99 111 108 111 114 
    32 91 91 99 111 108 111 114 40 48 41 93 93 59 10 125 
    59 10 10 115 116 114 117 99 116 32 109 97 105 110 48 95 
    105 110 10 123 10 32 32 32 32 102 108 111 97 116 52 32 
    99 111 108 111 114 32 91 91 117 115 101 114 40 108 111 99 
    110 48 41 93 93 59 10 125 59 10 10 102 114 97 103 109 
    101 110 116 32 109 97 105 110 48 95 111 117 116 32 109 97 
    105 110 48 40 109 97 105 110 48 95 105 110 32 105 110 32 
    91 91 115 116 97 103 101 95 105 110 93 93 41 10 123 10 
    32 32 32 32 109 97 105 110 48 95 111 117 116 32 111 117 
    116 32 61 32 123 125 59 10 32 32 32 32 111 117 116 46 
    102 114 97 103 95 99 111 108 111 114 32 61 32 105 110 46 
    99 111 108 111 114 59 10 32 32 32 32 114 101 116 117 114 
    110 32 111 117 116 59 10 125 10 10 0))

;; Cached shader descriptors for 'triangle'
(defvar *triangle-shader-desc-cache* (make-hash-table))

;; Shader descriptor function for 'triangle'
(defun triangle-shader-desc (backend)
  "Get shader descriptor for triangle shader (cached)"
  (or (gethash backend *triangle-shader-desc-cache*)
      (let ((desc (cffi:foreign-alloc '(:struct sg:sg-shader-desc))))
        ;; Zero out descriptor
        (loop for i from 0 below (cffi:foreign-type-size '(:struct sg:sg-shader-desc))
              do (setf (cffi:mem-aref desc :uint8 i) 0))
        
        ;; Set label
        (setf (cffi:foreign-slot-value desc '(:struct sg:sg-shader-desc) 'sg::label)
              (cffi:foreign-string-alloc "triangle_shader"))
        
        ;; Configure based on backend
        (case backend
      (:metal-macos ; metal_macos
       ;; vs stage
       (let ((func-ptr (cffi:foreign-slot-pointer desc '(:struct sg:sg-shader-desc) 'sg::vertex-func)))
         ;; Create source pointer from parameter
         (let ((src-data (cffi:foreign-alloc :uint8 :initial-contents +vs_source_metal_macos+)))
           (setf (cffi:foreign-slot-value func-ptr '(:struct sg:sg-shader-function) 'sg::source)
                 src-data))
         (setf (cffi:foreign-slot-value func-ptr '(:struct sg:sg-shader-function) 'sg::entry)
               (cffi:foreign-string-alloc "main0")))
       ;; fs stage
       (let ((func-ptr (cffi:foreign-slot-pointer desc '(:struct sg:sg-shader-desc) 'sg::fragment-func)))
         ;; Create source pointer from parameter
         (let ((src-data (cffi:foreign-alloc :uint8 :initial-contents +fs_source_metal_macos+)))
           (setf (cffi:foreign-slot-value func-ptr '(:struct sg:sg-shader-function) 'sg::source)
                 src-data))
         (setf (cffi:foreign-slot-value func-ptr '(:struct sg:sg-shader-function) 'sg::entry)
               (cffi:foreign-string-alloc "main0")))
       ;; Setup vertex attributes
       (let ((attrs-ptr (cffi:foreign-slot-pointer desc '(:struct sg:sg-shader-desc) 'sg::attrs)))
         (let ((attr0-ptr attrs-ptr))
           (setf (cffi:foreign-slot-value attr0-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr1-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 1)))
           (setf (cffi:foreign-slot-value attr1-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr2-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 2)))
           (setf (cffi:foreign-slot-value attr2-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr3-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 3)))
           (setf (cffi:foreign-slot-value attr3-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr4-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 4)))
           (setf (cffi:foreign-slot-value attr4-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr5-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 5)))
           (setf (cffi:foreign-slot-value attr5-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr6-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 6)))
           (setf (cffi:foreign-slot-value attr6-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr7-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 7)))
           (setf (cffi:foreign-slot-value attr7-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr8-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 8)))
           (setf (cffi:foreign-slot-value attr8-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr9-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 9)))
           (setf (cffi:foreign-slot-value attr9-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr10-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 10)))
           (setf (cffi:foreign-slot-value attr10-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr11-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 11)))
           (setf (cffi:foreign-slot-value attr11-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr12-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 12)))
           (setf (cffi:foreign-slot-value attr12-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr13-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 13)))
           (setf (cffi:foreign-slot-value attr13-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr14-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 14)))
           (setf (cffi:foreign-slot-value attr14-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
         (let ((attr15-ptr (cffi:mem-aptr attrs-ptr '(:struct sg:sg-shader-vertex-attr) 15)))
           (setf (cffi:foreign-slot-value attr15-ptr '(:struct sg:sg-shader-vertex-attr) 'sg::base-type)
                 (cffi:foreign-enum-value 'sg:sg-shader-attr-base-type :sg-shaderattrbasetype-float)))
       )
       )
          (otherwise
           (error "Unsupported backend: ~A" backend)))
        
        ;; Cache and return the descriptor
        (setf (gethash backend *triangle-shader-desc-cache*) desc)
        desc)))

