/* Generated by gen_cl.py -- part of cl-sokol https://github.com/takeiteasy/cl-sokol
   The MIT License (MIT)
   
   Copyright (c) 2023 George Watson
   
   Permission is hereby granted, free of charge, to any person
   obtaining a copy of this software and associated documentation
   files (the "Software"), to deal in the Software without restriction,
   including without limitation the rights to use, copy, modify, merge,
   publish, distribute, sublicense, and/or sell copies of the Software,
   and to permit persons to whom the Software is furnished to do so,
   subject to the following conditions:
   
   The above copyright notice and this permission notice shall be
   included in all copies or substantial portions of the Software.
   
   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
   EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
   MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
   IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
   CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
   TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
   SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */


#define SOKOL_IMPL
#include "sokol_fetch_cl.h"
sfetch_desc_t* sfetch_desc_cl(void) {
	sfetch_desc_t* result = malloc(sizeof(sfetch_desc_t));
	sfetch_desc_t tmp = sfetch_desc();
	memcpy(result, (void*)&tmp, sizeof(sfetch_desc_t));
	return result;
}
sfetch_handle_t* sfetch_send_cl(sfetch_request_t* a) {
	sfetch_handle_t* result = malloc(sizeof(sfetch_handle_t));
	sfetch_handle_t tmp = sfetch_send(a);
	memcpy(result, (void*)&tmp, sizeof(sfetch_handle_t));
	return result;
}
bool sfetch_handle_valid_cl(sfetch_handle_t* a) {
	return sfetch_handle_valid(*a);
}
void sfetch_bind_buffer_cl(sfetch_handle_t* a, sfetch_range_t* b) {
	sfetch_bind_buffer(*a, *b);
}
void* sfetch_unbind_buffer_cl(sfetch_handle_t* a) {
	return sfetch_unbind_buffer(*a);
}
void sfetch_cancel_cl(sfetch_handle_t* a) {
	sfetch_cancel(*a);
}
void sfetch_pause_cl(sfetch_handle_t* a) {
	sfetch_pause(*a);
}
void sfetch_continue_cl(sfetch_handle_t* a) {
	sfetch_continue(*a);
}
