;;;; package.lisp

(defpackage #:cl-sokol-bindings
  (:nicknames :%sokol)
  (:use #:cl #:cffi)
  (:export
   #:%sg-buffer
   #:%sg-image
   #:%sg-sampler
   #:%sg-shader
   #:%sg-pipeline
   #:%sg-pass
   #:%sg-context
   #:%sg-range
   #:%sg-color
   #:%sg-pixelformat-info
   #:%sg-features
   #:%sg-limits
   #:%sg-color-attachment-action
   #:%sg-depth-attachment-action
   #:%sg-stencil-attachment-action
   #:%sg-pass-action
   #:%sg-stage-bindings
   #:%sg-bindings
   #:%sg-buffer-desc
   #:%sg-image-data
   #:%sg-image-desc
   #:%sg-sampler-desc
   #:%sg-shader-attr-desc
   #:%sg-shader-uniform-desc
   #:%sg-shader-uniform-block-desc
   #:%sg-shader-image-desc
   #:%sg-shader-sampler-desc
   #:%sg-shader-image-sampler-pair-desc
   #:%sg-shader-stage-desc
   #:%sg-shader-desc
   #:%sg-vertex-buffer-layout-state
   #:%sg-vertex-attr-state
   #:%sg-vertex-layout-state
   #:%sg-stencil-face-state
   #:%sg-stencil-state
   #:%sg-depth-state
   #:%sg-blend-state
   #:%sg-color-target-state
   #:%sg-pipeline-desc
   #:%sg-pass-attachment-desc
   #:%sg-pass-desc
   #:%sg-trace-hooks
   #:%sg-slot-info
   #:%sg-buffer-info
   #:%sg-image-info
   #:%sg-sampler-info
   #:%sg-shader-info
   #:%sg-pipeline-info
   #:%sg-pass-info
   #:%sg-frame-stats-gl
   #:%sg-frame-stats-d3d11-pass
   #:%sg-frame-stats-d3d11-pipeline
   #:%sg-frame-stats-d3d11-bindings
   #:%sg-frame-stats-d3d11-uniforms
   #:%sg-frame-stats-d3d11-draw
   #:%sg-frame-stats-d3d11
   #:%sg-frame-stats-metal-idpool
   #:%sg-frame-stats-metal-pipeline
   #:%sg-frame-stats-metal-bindings
   #:%sg-frame-stats-metal-uniforms
   #:%sg-frame-stats-metal
   #:%sg-frame-stats-wgpu-uniforms
   #:%sg-frame-stats-wgpu-bindings
   #:%sg-frame-stats-wgpu
   #:%sg-frame-stats
   #:%sg-metal-context-desc
   #:%sg-d3d11-context-desc
   #:%sg-wgpu-context-desc
   #:%sg-gl-context-desc
   #:%sg-context-desc
   #:%sg-commit-listener
   #:%sg-allocator
   #:%sg-logger
   #:%sg-desc
   #:%sg-d3d11-buffer-info
   #:%sg-d3d11-image-info
   #:%sg-d3d11-sampler-info
   #:%sg-d3d11-shader-info
   #:%sg-d3d11-pipeline-info
   #:%sg-d3d11-pass-info
   #:%sg-mtl-buffer-info
   #:%sg-mtl-image-info
   #:%sg-mtl-sampler-info
   #:%sg-mtl-shader-info
   #:%sg-mtl-pipeline-info
   #:%sg-wgpu-buffer-info
   #:%sg-wgpu-image-info
   #:%sg-wgpu-sampler-info
   #:%sg-wgpu-shader-info
   #:%sg-wgpu-pipeline-info
   #:%sg-wgpu-pass-info
   #:%sg-gl-buffer-info
   #:%sg-gl-image-info
   #:%sg-gl-sampler-info
   #:%sg-gl-shader-info
   #:%sg-gl-pass-info
   #:%sapp-touchpoint
   #:%sapp-event
   #:%sapp-range
   #:%sapp-image-desc
   #:%sapp-icon-desc
   #:%sapp-allocator
   #:%sapp-logger
   #:%sapp-desc
   #:%sapp-html5-fetch-response
   #:%sapp-html5-fetch-request
   #:%saudio-logger
   #:%saudio-allocator
   #:%saudio-desc
   #:%sargs-allocator
   #:%sargs-desc
   #:%sfetch-logger-t
   #:%sfetch-range-t
   #:%sfetch-allocator-t
   #:%sfetch-desc-t
   #:%sfetch-handle-t
   #:%sfetch-response-t
   #:%sfetch-request-t
   #:sg-buffer
   #:sg-image
   #:sg-sampler
   #:sg-shader
   #:sg-pipeline
   #:sg-pass
   #:sg-context
   #:sg-range
   #:sg-color
   #:sg-pixelformat-info
   #:sg-features
   #:sg-limits
   #:sg-color-attachment-action
   #:sg-depth-attachment-action
   #:sg-stencil-attachment-action
   #:sg-pass-action
   #:sg-stage-bindings
   #:sg-bindings
   #:sg-buffer-desc
   #:sg-image-data
   #:sg-image-desc
   #:sg-sampler-desc
   #:sg-shader-attr-desc
   #:sg-shader-uniform-desc
   #:sg-shader-uniform-block-desc
   #:sg-shader-image-desc
   #:sg-shader-sampler-desc
   #:sg-shader-image-sampler-pair-desc
   #:sg-shader-stage-desc
   #:sg-shader-desc
   #:sg-vertex-buffer-layout-state
   #:sg-vertex-attr-state
   #:sg-vertex-layout-state
   #:sg-stencil-face-state
   #:sg-stencil-state
   #:sg-depth-state
   #:sg-blend-state
   #:sg-color-target-state
   #:sg-pipeline-desc
   #:sg-pass-attachment-desc
   #:sg-pass-desc
   #:sg-trace-hooks
   #:sg-slot-info
   #:sg-buffer-info
   #:sg-image-info
   #:sg-sampler-info
   #:sg-shader-info
   #:sg-pipeline-info
   #:sg-pass-info
   #:sg-frame-stats-gl
   #:sg-frame-stats-d3d11-pass
   #:sg-frame-stats-d3d11-pipeline
   #:sg-frame-stats-d3d11-bindings
   #:sg-frame-stats-d3d11-uniforms
   #:sg-frame-stats-d3d11-draw
   #:sg-frame-stats-d3d11
   #:sg-frame-stats-metal-idpool
   #:sg-frame-stats-metal-pipeline
   #:sg-frame-stats-metal-bindings
   #:sg-frame-stats-metal-uniforms
   #:sg-frame-stats-metal
   #:sg-frame-stats-wgpu-uniforms
   #:sg-frame-stats-wgpu-bindings
   #:sg-frame-stats-wgpu
   #:sg-frame-stats
   #:sg-metal-context-desc
   #:sg-d3d11-context-desc
   #:sg-wgpu-context-desc
   #:sg-gl-context-desc
   #:sg-context-desc
   #:sg-commit-listener
   #:sg-allocator
   #:sg-logger
   #:sg-desc
   #:sg-d3d11-buffer-info
   #:sg-d3d11-image-info
   #:sg-d3d11-sampler-info
   #:sg-d3d11-shader-info
   #:sg-d3d11-pipeline-info
   #:sg-d3d11-pass-info
   #:sg-mtl-buffer-info
   #:sg-mtl-image-info
   #:sg-mtl-sampler-info
   #:sg-mtl-shader-info
   #:sg-mtl-pipeline-info
   #:sg-wgpu-buffer-info
   #:sg-wgpu-image-info
   #:sg-wgpu-sampler-info
   #:sg-wgpu-shader-info
   #:sg-wgpu-pipeline-info
   #:sg-wgpu-pass-info
   #:sg-gl-buffer-info
   #:sg-gl-image-info
   #:sg-gl-sampler-info
   #:sg-gl-shader-info
   #:sg-gl-pass-info
   #:sapp-touchpoint
   #:sapp-event
   #:sapp-range
   #:sapp-image-desc
   #:sapp-icon-desc
   #:sapp-allocator
   #:sapp-logger
   #:sapp-desc
   #:sapp-html5-fetch-response
   #:sapp-html5-fetch-request
   #:saudio-logger
   #:saudio-allocator
   #:saudio-desc
   #:sargs-allocator
   #:sargs-desc
   #:sfetch-logger-t
   #:sfetch-range-t
   #:sfetch-allocator-t
   #:sfetch-desc-t
   #:sfetch-handle-t
   #:sfetch-response-t
   #:sfetch-request-t
   #:+sg-invalid-id+
   #:+sg-num-shader-stages+
   #:+sg-num-inflight-frames+
   #:+sg-max-color-attachments+
   #:+sg-max-vertex-buffers+
   #:+sg-max-shaderstage-images+
   #:+sg-max-shaderstage-samplers+
   #:+sg-max-shaderstage-imagesamplerpairs+
   #:+sg-max-shaderstage-ubs+
   #:+sg-max-ub-members+
   #:+sg-max-vertex-attributes+
   #:+sg-max-mipmaps+
   #:+sg-max-texturearray-layers+
   #:sg-backend
   #:sg-pixel-format
   #:sg-resource-state
   #:sg-usage
   #:sg-buffer-type
   #:sg-index-type
   #:sg-image-type
   #:sg-image-sample-type
   #:sg-sampler-type
   #:sg-cube-face
   #:sg-shader-stage
   #:sg-primitive-type
   #:sg-filter
   #:sg-wrap
   #:sg-border-color
   #:sg-vertex-format
   #:sg-vertex-step
   #:sg-uniform-type
   #:sg-uniform-layout
   #:sg-cull-mode
   #:sg-face-winding
   #:sg-compare-func
   #:sg-stencil-op
   #:sg-blend-factor
   #:sg-blend-op
   #:sg-color-mask
   #:sg-load-action
   #:sg-store-action
   #:sg-log-item
   #:+sapp-max-touchpoints+
   #:+sapp-max-mousebuttons+
   #:+sapp-max-keycodes+
   #:+sapp-max-iconimages+
   #:sapp-event-type
   #:sapp-keycode
   #:sapp-android-tooltype
   #:sapp-mousebutton
   #:+sapp-modifier-shift+
   #:+sapp-modifier-ctrl+
   #:+sapp-modifier-alt+
   #:+sapp-modifier-super+
   #:+sapp-modifier-lmb+
   #:+sapp-modifier-rmb+
   #:+sapp-modifier-mmb+
   #:sapp-log-item
   #:sapp-html5-fetch-error
   #:sapp-mouse-cursor
   #:saudio-log-item
   #:sfetch-log-item-t
   #:sfetch-error-t
   #:sg-setup
   #:sg-shutdown
   #:sg-isvalid
   #:sg-reset-state-cache
   #:sg-install-trace-hooks
   #:sg-push-debug-group
   #:sg-pop-debug-group
   #:sg-add-commit-listener
   #:sg-remove-commit-listener
   #:sg-make-buffer
   #:sg-make-image
   #:sg-make-sampler
   #:sg-make-shader
   #:sg-make-pipeline
   #:sg-make-pass
   #:sg-destroy-buffer
   #:sg-destroy-image
   #:sg-destroy-sampler
   #:sg-destroy-shader
   #:sg-destroy-pipeline
   #:sg-destroy-pass
   #:sg-update-buffer
   #:sg-update-image
   #:sg-append-buffer
   #:sg-query-buffer-overflow
   #:sg-query-buffer-will-overflow
   #:sg-begin-default-pass
   #:sg-begin-default-passf
   #:sg-begin-pass
   #:sg-apply-viewport
   #:sg-apply-viewportf
   #:sg-apply-scissor-rect
   #:sg-apply-scissor-rectf
   #:sg-apply-pipeline
   #:sg-apply-bindings
   #:sg-apply-uniforms
   #:sg-draw
   #:sg-end-pass
   #:sg-commit
   #:sg-query-desc
   #:sg-query-backend
   #:sg-query-features
   #:sg-query-limits
   #:sg-query-pixelformat
   #:sg-query-buffer-state
   #:sg-query-image-state
   #:sg-query-sampler-state
   #:sg-query-shader-state
   #:sg-query-pipeline-state
   #:sg-query-pass-state
   #:sg-query-buffer-info
   #:sg-query-image-info
   #:sg-query-sampler-info
   #:sg-query-shader-info
   #:sg-query-pipeline-info
   #:sg-query-pass-info
   #:sg-query-buffer-desc
   #:sg-query-image-desc
   #:sg-query-sampler-desc
   #:sg-query-shader-desc
   #:sg-query-pipeline-desc
   #:sg-query-pass-desc
   #:sg-query-buffer-defaults
   #:sg-query-image-defaults
   #:sg-query-sampler-defaults
   #:sg-query-shader-defaults
   #:sg-query-pipeline-defaults
   #:sg-query-pass-defaults
   #:sg-alloc-buffer
   #:sg-alloc-image
   #:sg-alloc-sampler
   #:sg-alloc-shader
   #:sg-alloc-pipeline
   #:sg-alloc-pass
   #:sg-dealloc-buffer
   #:sg-dealloc-image
   #:sg-dealloc-sampler
   #:sg-dealloc-shader
   #:sg-dealloc-pipeline
   #:sg-dealloc-pass
   #:sg-init-buffer
   #:sg-init-image
   #:sg-init-sampler
   #:sg-init-shader
   #:sg-init-pipeline
   #:sg-init-pass
   #:sg-uninit-buffer
   #:sg-uninit-image
   #:sg-uninit-sampler
   #:sg-uninit-shader
   #:sg-uninit-pipeline
   #:sg-uninit-pass
   #:sg-fail-buffer
   #:sg-fail-image
   #:sg-fail-sampler
   #:sg-fail-shader
   #:sg-fail-pipeline
   #:sg-fail-pass
   #:sg-enable-frame-stats
   #:sg-disable-frame-stats
   #:sg-frame-stats-enabled
   #:sg-query-frame-stats
   #:sg-setup-context
   #:sg-activate-context
   #:sg-discard-context
   #:sg-d3d11-device
   #:sg-d3d11-device-context
   #:sg-d3d11-query-buffer-info
   #:sg-d3d11-query-image-info
   #:sg-d3d11-query-sampler-info
   #:sg-d3d11-query-shader-info
   #:sg-d3d11-query-pipeline-info
   #:sg-d3d11-query-pass-info
   #:sg-mtl-device
   #:sg-mtl-render-command-encoder
   #:sg-mtl-query-buffer-info
   #:sg-mtl-query-image-info
   #:sg-mtl-query-sampler-info
   #:sg-mtl-query-shader-info
   #:sg-mtl-query-pipeline-info
   #:sg-wgpu-device
   #:sg-wgpu-queue
   #:sg-wgpu-command-encoder
   #:sg-wgpu-render-pass-encoder
   #:sg-wgpu-query-buffer-info
   #:sg-wgpu-query-image-info
   #:sg-wgpu-query-sampler-info
   #:sg-wgpu-query-shader-info
   #:sg-wgpu-query-pipeline-info
   #:sg-wgpu-query-pass-info
   #:sg-gl-query-buffer-info
   #:sg-gl-query-image-info
   #:sg-gl-query-sampler-info
   #:sg-gl-query-shader-info
   #:sg-gl-query-pass-info
   #:sapp-isvalid
   #:sapp-width
   #:sapp-widthf
   #:sapp-height
   #:sapp-heightf
   #:sapp-color-format
   #:sapp-depth-format
   #:sapp-sample-count
   #:sapp-high-dpi
   #:sapp-dpi-scale
   #:sapp-show-keyboard
   #:sapp-keyboard-shown
   #:sapp-is-fullscreen
   #:sapp-toggle-fullscreen
   #:sapp-show-mouse
   #:sapp-mouse-shown
   #:sapp-lock-mouse
   #:sapp-mouse-locked
   #:sapp-set-mouse-cursor
   #:sapp-get-mouse-cursor
   #:sapp-userdata
   #:sapp-query-desc
   #:sapp-request-quit
   #:sapp-cancel-quit
   #:sapp-quit
   #:sapp-consume-event
   #:sapp-frame-count
   #:sapp-frame-duration
   #:sapp-set-clipboard-string
   #:sapp-get-clipboard-string
   #:sapp-set-window-title
   #:sapp-set-icon
   #:sapp-get-num-dropped-files
   #:sapp-get-dropped-file-path
   #:sapp-run
   #:sapp-egl-get-display
   #:sapp-egl-get-context
   #:sapp-html5-ask-leave-site
   #:sapp-html5-get-dropped-file-size
   #:sapp-html5-fetch-dropped-file
   #:sapp-metal-get-device
   #:sapp-metal-get-renderpass-descriptor
   #:sapp-metal-get-drawable
   #:sapp-macos-get-window
   #:sapp-ios-get-window
   #:sapp-d3d11-get-device
   #:sapp-d3d11-get-device-context
   #:sapp-d3d11-get-swap-chain
   #:sapp-d3d11-get-render-target-view
   #:sapp-d3d11-get-depth-stencil-view
   #:sapp-win32-get-hwnd
   #:sapp-wgpu-get-device
   #:sapp-wgpu-get-render-view
   #:sapp-wgpu-get-resolve-view
   #:sapp-wgpu-get-depth-stencil-view
   #:sapp-android-get-native-activity
   #:saudio-setup
   #:saudio-shutdown
   #:saudio-isvalid
   #:saudio-userdata
   #:saudio-query-desc
   #:saudio-sample-rate
   #:saudio-buffer-frames
   #:saudio-channels
   #:saudio-suspended
   #:saudio-expect
   #:saudio-push
   #:stm-setup
   #:stm-now
   #:stm-diff
   #:stm-since
   #:stm-laptime
   #:stm-round-to-common-refresh-rate
   #:stm-sec
   #:stm-ms
   #:stm-us
   #:stm-ns
   #:sargs-setup
   #:sargs-shutdown
   #:sargs-isvalid
   #:sargs-exists
   #:sargs-value
   #:sargs-value-def
   #:sargs-equals
   #:sargs-boolean
   #:sargs-find
   #:sargs-num-args
   #:sargs-key-at
   #:sargs-value-at
   #:sfetch-setup
   #:sfetch-shutdown
   #:sfetch-valid
   #:sfetch-desc
   #:sfetch-max-userdata-bytes
   #:sfetch-max-path
   #:sfetch-send
   #:sfetch-handle-valid
   #:sfetch-dowork
   #:sfetch-bind-buffer
   #:sfetch-unbind-buffer
   #:sfetch-cancel
   #:sfetch-pause
   #:sfetch-continue
   #:sokol-default-sgdesc))

(defpackage #:cl-sokol
  (:nicknames :sokol)
  (:use #:cl #:cffi #:%sokol)
  (:export
   #:run
   #:init-cb
   #:frame-cb
   #:event-cb
   #:cleanup-cb))

(defpackage #:cl-sokol-test
  (:nicknames :sokol-test)
  (:use #:cl)
  (:export #:run))