;;;; Auto-generated CFFI bindings for Sokol
;;;; DO NOT EDIT - generated by gen_lisp.py

(defpackage :sokol-gfx-imgui
  (:use :cl :cffi)
  (:nicknames :sgimgui)
  (:export
   sgimgui-allocator
   sgimgui-desc
   sgimgui-draw
   sgimgui-draw-buffer-menu-item
   sgimgui-draw-buffer-window
   sgimgui-draw-buffer-window-content
   sgimgui-draw-capabilities-menu-item
   sgimgui-draw-capabilities-window
   sgimgui-draw-capabilities-window-content
   sgimgui-draw-capture-menu-item
   sgimgui-draw-capture-window
   sgimgui-draw-capture-window-content
   sgimgui-draw-frame-stats-menu-item
   sgimgui-draw-frame-stats-window
   sgimgui-draw-frame-stats-window-content
   sgimgui-draw-image-menu-item
   sgimgui-draw-image-window
   sgimgui-draw-image-window-content
   sgimgui-draw-menu
   sgimgui-draw-pipeline-menu-item
   sgimgui-draw-pipeline-window
   sgimgui-draw-pipeline-window-content
   sgimgui-draw-sampler-menu-item
   sgimgui-draw-sampler-window
   sgimgui-draw-sampler-window-content
   sgimgui-draw-shader-menu-item
   sgimgui-draw-shader-window
   sgimgui-draw-shader-window-content
   sgimgui-draw-view-menu-item
   sgimgui-draw-view-window
   sgimgui-draw-view-window-content
   sgimgui-setup
   sgimgui-shutdown
   ))

(in-package :sokol-gfx-imgui)

;;;; Original header documentation:
;;;; sokol_gfx_imgui.h -- debug-inspection UI for sokol_gfx.h using Dear ImGui
;;;; 
;;;;     Project URL: https://github.com/floooh/sokol
;;;; 
;;;;     Do this:
;;;;         #define SOKOL_IMPL or
;;;;         #define SOKOL_GFX_IMGUI_IMPL
;;;; 
;;;;     before you include this file in *one* C or C++ file to create the
;;;;     implementation.
;;;; 
;;;;     NOTE that the implementation can be compiled either as C++ or as C.
;;;;     When compiled as C++, sokol_gfx_imgui.h will directly call into the
;;;;     Dear ImGui C++ API. When compiled as C, sokol_gfx_imgui.h will call
;;;;     cimgui.h functions instead.
;;;; 
;;;;     Include the following file(s) before including sokol_gfx_imgui.h:
;;;; 
;;;;         sokol_gfx.h
;;;; 
;;;;     Additionally, include the following headers before including the
;;;;     implementation:
;;;; 
;;;;     If the implementation is compiled as C++:
;;;;         imgui.h
;;;; 
;;;;     If the implementation is compiled as C:
;;;;         cimgui.h
;;;; 
;;;;     The sokol_gfx.h implementation must be compiled with debug trace hooks
;;;;     enabled by defining:
;;;; 
;;;;         SOKOL_TRACE_HOOKS
;;;; 
;;;;     ...before including the sokol_gfx.h implementation.
;;;; 
;;;;     Before including the sokol_gfx_imgui.h implementation, optionally
;;;;     override the following macros:
;;;; 
;;;;         SOKOL_ASSERT(c)     -- your own assert macro, default: assert(c)
;;;;         SOKOL_UNREACHABLE   -- your own macro to annotate unreachable code,
;;;;                                default: SOKOL_ASSERT(false)
;;;;         SOKOL_GFX_IMGUI_API_DECL    - public function declaration prefix (default: extern)
;;;;         SOKOL_GFX_IMGUI_CPREFIX     - defines the function prefix for the Dear ImGui C bindings (default: ig)
;;;;         SOKOL_API_DECL      - same as SOKOL_GFX_IMGUI_API_DECL
;;;;         SOKOL_API_IMPL      - public function implementation prefix (default: -)
;;;; 
;;;;     If sokol_gfx_imgui.h is compiled as a DLL, define the following before
;;;;     including the declaration or implementation:
;;;; 
;;;;     SOKOL_DLL
;;;; 
;;;;     On Windows, SOKOL_DLL will define SOKOL_GFX_IMGUI_API_DECL as __declspec(dllexport)
;;;;     or __declspec(dllimport) as needed.
;;;; 
;;;;     STEP BY STEP:
;;;;     =============
;;;;     --- call sgimgui_init() with optional allocator overrides:
;;;; 
;;;;             sgimgui_init(&(sgimgui_desc_t){
;;;;                 .allocator = {
;;;;                     .alloc_fn = my_malloc,
;;;;                     .free_fn = my_free,
;;;;                 }
;;;;             });
;;;; 
;;;;     --- somewhere in the per-frame code call:
;;;; 
;;;;             sgimgui_draw()
;;;; 
;;;;         this won't draw anything yet, since no windows are open.
;;;; 
;;;;     --- call the convenience function sgimgui_draw_menu(ctx, title)
;;;;         to render a menu which allows to open/close the provided debug windows
;;;; 
;;;;             sgimgui_draw_menu("sokol-gfx");
;;;; 
;;;;     --- alternatively the individual single menu items via:
;;;; 
;;;;         if (ImGui::BeginMainMenuBar()) {
;;;;             if (ImGui::BeginMenu("sokol-gfx")) {
;;;;                 sgimgui_draw_buffer_window_menu_item("Buffers");
;;;;                 sgimgui_draw_image_window_menu_item("Images");
;;;;                 sgimgui_draw_sampler_window_menu_item("Samplers");
;;;;                 sgimgui_draw_shader_window_menu_item("Shaders");
;;;;                 sgimgui_draw_pipeline_window_menu_item("Pipelines");
;;;;                 sgimgui_draw_view_window_menu_item("Views");
;;;;                 sgimgui_draw_capture_window_menu_item("Calls");
;;;;                 sgimgui_draw_capabilities_window_menu_item("Capabilities");
;;;;                 sgimgui_draw_frame_stats_window_menu_item("Frame Stats");
;;;;                 ImGui::EndMenu();
;;;;             }
;;;;             ImGui::EndMainMenuBar();
;;;;         }
;;;; 
;;;;     --- before application shutdown, call:
;;;; 
;;;;             sgimgui_discard();
;;;; 
;;;;         ...this is not strictly necessary because the application exits
;;;;         anyway, but not doing this may trigger memory leak detection tools.
;;;; 
;;;;     --- finally, your application needs an ImGui renderer, you can either
;;;;         provide your own, or drop in the sokol_imgui.h utility header
;;;; 
;;;;     ALTERNATIVE DRAWING FUNCTIONS:
;;;;     ==============================
;;;;     Instead of the convenient but all-in-one sgimgui_draw() function,
;;;;     you can also use the following granular functions which might allow
;;;;     better integration with your existing UI:
;;;; 
;;;;     The following functions only render the window *content* (so you
;;;;     can integrate the UI into you own windows):
;;;; 
;;;;         void sgimgui_draw_buffer_window_content();
;;;;         void sgimgui_draw_image_window_content();
;;;;         void sgimgui_draw_sampler_window_content();
;;;;         void sgimgui_draw_shader_window_content();
;;;;         void sgimgui_draw_pipeline_window_content();
;;;;         void sgimgui_draw_view_window_content();
;;;;         void sgimgui_draw_capture_window_content();
;;;;         void sgimgui_draw_capabilities_window_content();
;;;;         void sgimgui_draw_frame_stats_window_content();
;;;; 
;;;;     And these are the 'full window' drawing functions:
;;;; 
;;;;         void sgimgui_draw_buffer_window("Buffers");
;;;;         void sgimgui_draw_image_window("Images");
;;;;         void sgimgui_draw_sampler_window("Samplers");
;;;;         void sgimgui_draw_shader_window("Shaders");
;;;;         void sgimgui_draw_pipeline_window("Pipelines");
;;;;         void sgimgui_draw_view_window("Views");
;;;;         void sgimgui_draw_capture_window("Frame Capture");
;;;;         void sgimgui_draw_capabilities_window("Capabilities");
;;;;         void sgimgui_draw_frame_stats_window("Frame Stats");
;;;; 
;;;;     Finer-grained drawing functions may be moved to the public API
;;;;     in the future as needed.
;;;; 
;;;;     LICENSE
;;;;     =======
;;;;     zlib/libpng license
;;;; 
;;;;     Copyright (c) 2018 Andre Weissflog
;;;; 
;;;;     This software is provided 'as-is', without any express or implied warranty.
;;;;     In no event will the authors be held liable for any damages arising from the
;;;;     use of this software.
;;;; 
;;;;     Permission is granted to anyone to use this software for any purpose,
;;;;     including commercial applications, and to alter it and redistribute it
;;;;     freely, subject to the following restrictions:
;;;; 
;;;;         1. The origin of this software must not be misrepresented; you must not
;;;;         claim that you wrote the original software. If you use this software in a
;;;;         product, an acknowledgment in the product documentation would be
;;;;         appreciated but is not required.
;;;; 
;;;;         2. Altered source versions must be plainly marked as such, and must not
;;;;         be misrepresented as being the original software.
;;;; 
;;;;         3. This notice may not be removed or altered from any source
;;;;         distribution.

;; Enums and Constants

;; Structs

(cffi:defcstruct sgimgui-allocator
  ;; sgimgui_allocator_t
  (alloc-fn :pointer)
  (free-fn :pointer)
  (user-data :pointer)
)

(cffi:defcstruct sgimgui-desc
  ;; sgimgui_desc_t
  (allocator (:struct sgimgui-allocator))
)

;; Functions

(cffi:defcfun ("sgimgui_setup" sgimgui-setup) :void
  (desc (:pointer (:struct sgimgui-desc)))
)

(cffi:defcfun ("sgimgui_shutdown" sgimgui-shutdown) :void
)

(cffi:defcfun ("sgimgui_draw" sgimgui-draw) :void
)

(cffi:defcfun ("sgimgui_draw_menu" sgimgui-draw-menu) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_buffer_window_content" sgimgui-draw-buffer-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_image_window_content" sgimgui-draw-image-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_sampler_window_content" sgimgui-draw-sampler-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_shader_window_content" sgimgui-draw-shader-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_pipeline_window_content" sgimgui-draw-pipeline-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_view_window_content" sgimgui-draw-view-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_capture_window_content" sgimgui-draw-capture-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_capabilities_window_content" sgimgui-draw-capabilities-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_frame_stats_window_content" sgimgui-draw-frame-stats-window-content) :void
)

(cffi:defcfun ("sgimgui_draw_buffer_window" sgimgui-draw-buffer-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_image_window" sgimgui-draw-image-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_sampler_window" sgimgui-draw-sampler-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_shader_window" sgimgui-draw-shader-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_pipeline_window" sgimgui-draw-pipeline-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_view_window" sgimgui-draw-view-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_capture_window" sgimgui-draw-capture-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_capabilities_window" sgimgui-draw-capabilities-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_frame_stats_window" sgimgui-draw-frame-stats-window) :void
  (title :string)
)

(cffi:defcfun ("sgimgui_draw_buffer_menu_item" sgimgui-draw-buffer-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_image_menu_item" sgimgui-draw-image-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_sampler_menu_item" sgimgui-draw-sampler-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_shader_menu_item" sgimgui-draw-shader-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_pipeline_menu_item" sgimgui-draw-pipeline-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_view_menu_item" sgimgui-draw-view-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_capture_menu_item" sgimgui-draw-capture-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_capabilities_menu_item" sgimgui-draw-capabilities-menu-item) :void
  (label :string)
)

(cffi:defcfun ("sgimgui_draw_frame_stats_menu_item" sgimgui-draw-frame-stats-menu-item) :void
  (label :string)
)

